version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
  version: 2
  build-n-deploy: # The build job runs for all branches and all tags. The deploy job runs for no branches and only for tags starting with ‘v’.
    jobs:
      - build:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
